/**
 * Demo Products for Kasparex Store
 * These are sample products to showcase the store functionality
 */

import type { Product } from './types';

export const demoProducts: Omit<Product, 'id' | 'slug' | 'createdAt' | 'purchaseCount' | 'listingFeePaid'>[] = [
  {
    title: 'Kaspa Node Setup Guide',
    description: 'Complete step-by-step guide for setting up and running a Kaspa node. Includes configuration, optimization tips, and troubleshooting.',
    content: 'This comprehensive guide covers everything you need to know about running a Kaspa node. Learn about hardware requirements, network configuration, and best practices for optimal performance.',
    sellerAddress: 'kaspa:demo1',
    priceKAS: 25,
    network: 'L1',
    category: 'Software',
    assetCids: [],
    thumbnailCid: '',
    status: 'active',
  },
  {
    title: 'Kasparex Ecosystem Art Pack',
    description: 'High-quality digital art collection featuring Kasparex branding, logos, and ecosystem visuals. Perfect for creators and developers.',
    content: 'This art pack includes:\n- Vector logos in multiple formats\n- Social media templates\n- Banner designs\n- Icon sets\n- Brand guidelines',
    sellerAddress: 'kaspa:demo2',
    priceKAS: 50,
    network: 'L1',
    category: 'Art',
    assetCids: [],
    thumbnailCid: '',
    status: 'active',
  },
  {
    title: 'Kaspa Blockchain Music Track',
    description: 'Original electronic music track inspired by Kaspa blockchain technology. High-quality WAV and MP3 formats included.',
    content: 'Experience the sound of Kaspa with this original composition. Includes:\n- Master WAV file (24-bit/96kHz)\n- MP3 version (320kbps)\n- Stems for remixing\n- License for commercial use',
    sellerAddress: 'kaspa:demo3',
    priceKAS: 15,
    network: 'L2',
    category: 'Music',
    assetCids: [],
    thumbnailCid: '',
    status: 'active',
  },
  {
    title: 'Next.js dApp Template',
    description: 'Production-ready Next.js template for building Kaspa dApps. Includes wallet integration, IPFS support, and TypeScript setup.',
    content: 'Get started quickly with this comprehensive template:\n- Next.js 15 with App Router\n- Kaspa wallet integration\n- IPFS client setup\n- TypeScript configuration\n- Tailwind CSS styling\n- Example components',
    sellerAddress: 'kaspa:demo4',
    priceKAS: 100,
    network: 'L2',
    category: 'Templates',
    assetCids: [],
    thumbnailCid: '',
    status: 'active',
  },
  {
    title: 'KREX Token Economics Analysis',
    description: 'In-depth analysis of KREX tokenomics, reward mechanisms, and economic models. Includes charts and projections.',
    content: 'This detailed analysis covers:\n- Token distribution models\n- Reward calculation formulas\n- Fee reduction mechanics\n- NFT integration benefits\n- Future roadmap implications',
    sellerAddress: 'kaspa:demo1',
    priceKAS: 75,
    paymentCurrency: 'KREX',
    network: 'L1',
    category: 'Other',
    assetCids: [],
    thumbnailCid: '',
    status: 'active',
  },
  {
    title: 'Kaspa Smart Contract Examples',
    description: 'Collection of smart contract examples for Kaspa L2. Includes DeFi, NFT, and token contract templates with documentation.',
    content: 'Learn from real-world examples:\n- ERC-20 token contract\n- NFT collection contract\n- Staking contract\n- Multi-signature wallet\n- All with detailed comments',
    sellerAddress: 'kaspa:demo2',
    priceKAS: 150,
    network: 'L2',
    category: 'Software',
    assetCids: [],
    thumbnailCid: '',
    status: 'active',
  },
  {
    title: 'Kasparex UI Component Library',
    description: 'Reusable React components matching Kasparex design system. Includes buttons, cards, modals, and form elements.',
    content: 'Build consistent UIs with:\n- 30+ pre-built components\n- Dark mode support\n- Responsive design\n- TypeScript types\n- Storybook documentation',
    sellerAddress: 'kaspa:demo3',
    priceKAS: 60,
    network: 'L1',
    category: 'Templates',
    assetCids: [],
    thumbnailCid: '',
    status: 'active',
  },
  {
    title: 'Kaspa Network Visualization',
    description: 'Animated visualization of the Kaspa DAG structure and network topology. Perfect for presentations and educational content.',
    content: 'This visualization includes:\n- Interactive DAG explorer\n- Network topology map\n- Block propagation animation\n- Mining visualization\n- Export options (PNG, SVG, MP4)',
    sellerAddress: 'kaspa:demo4',
    priceKAS: 40,
    network: 'L1',
    category: 'Art',
    assetCids: [],
    thumbnailCid: '',
    status: 'active',
  },
];
