'use client';

import Link from 'next/link';
import { DEMO_LABELS } from '@/lib/revenue-tree/mockFlowData';
import { formatEther } from 'viem';

export interface RevenueTreeFlowLevelModalRow {
  level: number;
  sharePct: number;
  wallet: string;
  isYou: boolean;
  treesAtLevel: number;
  revenueShareWei?: string;
  treeSlugsAtLevel: string[];
}

export interface RevenueTreeFlowLevelModalProps {
  isOpen: boolean;
  onClose: () => void;
  row: RevenueTreeFlowLevelModalRow | null;
  treeIdLabel: string;
  symbol: string;
  walletDisplay: (addr: string) => string;
}

export function RevenueTreeFlowLevelModal({
  isOpen,
  onClose,
  row,
  treeIdLabel,
  symbol,
  walletDisplay,
}: RevenueTreeFlowLevelModalProps) {
  if (!isOpen || !row) return null;

  const shareInKas = row.revenueShareWei
    ? parseFloat(formatEther(BigInt(row.revenueShareWei))).toLocaleString(undefined, { maximumFractionDigits: 2 })
    : '—';

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" onClick={onClose}>
      <div
        className="bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-2xl max-w-md w-full max-h-[90vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-6 border-b border-zinc-100 dark:border-zinc-800 flex items-center justify-between bg-zinc-50/50 dark:bg-zinc-900/50">
          <div>
            <h3 className="text-xl font-black text-zinc-900 dark:text-zinc-100 uppercase tracking-tight">
              Level {row.level} Details
            </h3>
            <p className="text-xs font-bold text-[#02abb8] uppercase tracking-widest mt-1">
              {row.sharePct}% Revenue Multiplier
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-2 rounded-xl text-zinc-500 hover:bg-zinc-200 dark:hover:bg-zinc-800 transition-colors"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {/* Quick Stats Grid */}
          <div className="grid grid-cols-2 gap-4">
             <div className="p-4 rounded-2xl bg-zinc-50 dark:bg-zinc-800/50 border border-zinc-100 dark:border-zinc-700">
                <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block mb-1">Accumulated Share</span>
                <span className="text-lg font-black text-[#02abb8] tabular-nums">{shareInKas} {symbol}</span>
             </div>
             <div className="p-4 rounded-2xl bg-zinc-50 dark:bg-zinc-800/50 border border-zinc-100 dark:border-zinc-700">
                <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block mb-1">Downline Nodes</span>
                <span className="text-lg font-black text-purple-600 dark:text-purple-400 tabular-nums">{row.treesAtLevel.toLocaleString()}</span>
             </div>
          </div>

          <div className="space-y-4">
            <div className="p-4 rounded-2xl bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800">
               <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block mb-2">Occupying Wallet</span>
               <div className="flex items-center gap-2">
                 <div className="w-8 h-8 rounded-full bg-zinc-100 dark:bg-zinc-800 flex items-center justify-center shrink-0">
                    <svg className="w-4 h-4 text-zinc-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                 </div>
                 <span className="text-sm font-mono font-bold text-zinc-900 dark:text-zinc-100 truncate flex-1">{walletDisplay(row.wallet)}</span>
               </div>
            </div>

            <p className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed italic">
              {row.level === 1
                ? 'This is your direct referrer position. In our system, your direct L1 never earns from your own spend volume; rewards are instead pushed up to L2–L5.'
                : `You are currently positioned at L${row.level} within the trees generated by your downline referrals. You receive ${row.sharePct}% of their native spend volume.`}
            </p>
          </div>

          {row.treeSlugsAtLevel.length > 0 && (
            <div className="pt-4 border-t border-zinc-100 dark:border-zinc-800">
              <h4 className="text-[10px] font-black text-zinc-400 uppercase tracking-widest mb-4">Network Node Directory</h4>
              <div className="space-y-2">
                {row.treeSlugsAtLevel.map((slug) => (
                  <Link
                    key={slug}
                    href={`/tree/flow/${slug}`}
                    className="flex items-center justify-between p-3 rounded-xl bg-zinc-50 dark:bg-zinc-800/30 border border-zinc-100 dark:border-zinc-700 hover:border-[#02abb8] group transition-all"
                    onClick={onClose}
                  >
                    <div className="flex items-center gap-3">
                        <div className="w-6 h-6 rounded-lg bg-white dark:bg-zinc-900 border border-zinc-100 dark:border-zinc-800 flex items-center justify-center text-[10px] font-black text-zinc-400">
                           {slug.split('-')[1]?.toUpperCase() || 'ID'}
                        </div>
                        <span className="text-sm font-bold text-zinc-700 dark:text-zinc-300">Tree {DEMO_LABELS[slug] ?? slug}</span>
                    </div>
                    <svg className="w-4 h-4 text-zinc-300 group-hover:text-[#02abb8] group-hover:translate-x-1 transition-all" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M9 5l7 7-7 7" />
                    </svg>
                  </Link>
                ))}
              </div>
            </div>
          )}

          {row.treeSlugsAtLevel.length === 0 && row.treesAtLevel === 0 && (
            <div className="py-8 text-center bg-zinc-50 dark:bg-zinc-800/20 rounded-2xl border border-dashed border-zinc-200 dark:border-zinc-800">
                <p className="text-xs font-bold text-zinc-400 uppercase tracking-wider">No nodes detected at this depth</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
